apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc.yaml
spec:
  storageClassName: nfs-csi-retain
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 25Gi
