falco:
  metrics:
    enabled: true
    service:
      create: true
  grafana:
    dashboards:
      enabled: true
      configMaps:
        falco:
          namespace: prometheus-stack
  serviceMonitor:
    create: true
    namespace: prometheus-stack
    labels:
      release: kube-prometheus-stack
