apiVersion: v1
data:
  config.alloy: |
    logging {
      level = "info"
      format = "logfmt"
    }

    loki.write "default" {
      endpoint {
        url = "https://in-cluster-loki.svc.loki.cluster.local/loki/api/v1/push"
      }
    }

    discovery.kubernetes "pods" {
        role = "pod"
    }

    discovery.kubernetes "nodes" {
        role = "node"
    }

    discovery.kubernetes "services" {
        role = "service"
    }

    discovery.kubernetes "endpoints" {
        role = "endpoints"
    }

    discovery.kubernetes "endpointslices" {
        role = "endpointslice"
    }

    discovery.kubernetes "ingresses" {
        role = "ingress"
    }

kind: ConfigMap
metadata:
  name: alloy-config
  namespace: alloy
