minio:
  replicas: 4
  persistence:
    enabled: true
    storageClass: nfs-csi-retain
    size: 100Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - minio.home.kevinbreit.net
    tls:
      - secretName: minio-tls
        hosts:
          - minio.home.kevinbreit.net
  consoleIngress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - minio-ui.home.kevinbreit.net
    tls:
      - secretName: minio-ui-tls
        hosts:
          - minio-ui.home.kevinbreit.net
  resources:
    requests:
      memory: 8Gi
