crds:
  enabled: false
prometheus:
  enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-csi-retain
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 25Gi
