kube-prometheus-stack:
  crds:
    enabled: false
  prometheusOperator:
    enabled: true
    admissionWebhooks:
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
      patch:
        annotations:
          argocd.argoproj.io/hook: PreSync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
    mutatingWebhookConfiguration:
      annotations:
        argocd.argoproj.io/hook: PreSync
      validatingWebhookConfiguration:
        annotations:
          argocd.argoproj.io/hook: PreSync
  prometheus:
    enabled: true
    prometheusSpec:
      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-csi-retain
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 25Gi
