apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{.name}}-cert-manager"
      annotations:
        name: "{{.name}}-cert-manager"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/kbreit/k8s-infra/
        targetRevision: HEAD
        path: infra/cert-manager
      destination:
        server: "https://kubernetes.default.svc"
        namespace: cert-manager
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Replace=false
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
