apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            minio: "true"
  template:
    metadata:
      name: "{{.name}}-minio"
      annotations:
        name: "{{.name}}-minio"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/kbreit/k8s-infra/
        targetRevision: HEAD
        path: infra/minio
      destination:
        server: "https://kubernetes.default.svc"
        namespace: minio
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Replace=false
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
